
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.lang.Object;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author deepbhai
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        maleFemale();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fNameSignUp = new javax.swing.JTextField();
        addressSignUp = new javax.swing.JTextField();
        usernameSignUp = new javax.swing.JTextField();
        lNameSignUp = new javax.swing.JTextField();
        maleSignUp = new javax.swing.JRadioButton();
        femaleSignUp = new javax.swing.JRadioButton();
        passwordSignUp = new javax.swing.JPasswordField();
        btnRegisterSignUp = new javax.swing.JButton();
        btnBackToLogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        phoneSignUp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        emailSignUp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Gender");

        jLabel4.setText("Address");

        jLabel5.setText("Username");

        jLabel6.setText("Password");

        maleSignUp.setText("Male");
        maleSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleSignUpActionPerformed(evt);
            }
        });

        femaleSignUp.setText("Female");

        btnRegisterSignUp.setText("Register");
        btnRegisterSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterSignUpActionPerformed(evt);
            }
        });

        btnBackToLogin.setText("Back");
        btnBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToLoginActionPerformed(evt);
            }
        });

        jLabel7.setText("Email");

        jLabel8.setText("Phone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnBackToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegisterSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(maleSignUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(femaleSignUp))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lNameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(addressSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(fNameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8))
                                    .addGap(27, 27, 27))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usernameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(phoneSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fNameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lNameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleSignUp)
                    .addComponent(femaleSignUp)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addressSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(usernameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(passwordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emailSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(phoneSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterSignUpActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        if(lg.checkIfDatabaseexist()){
            String fName = fNameSignUp.getText();
            String lName = lNameSignUp.getText();
            String address = addressSignUp.getText();
            String username = usernameSignUp.getText();
            String password = passwordSignUp.getText();
            String email = emailSignUp.getText();
            String phone = phoneSignUp.getText();
            String gender;
        
        //Get the text of Radio button
            if(maleSignUp.isSelected()){
                gender = maleSignUp.getText();
            }else{
                gender = femaleSignUp.getText();
            }
        
            boolean maleFemaleCheck = maleFemale();
        
            if(checkIfValueCorrect(fName,lName,address,username,password,email,phone,maleFemaleCheck)){
                //Checks If Username already exist
                Connection cn = DatabaseConnection.getConnection();
                try{
                    Statement stat = cn.createStatement();
                    ResultSet rs = stat.executeQuery("select * from LoginUsers where Username='"+username+"'");
                    if(rs.next()){
                        JOptionPane.showMessageDialog(null, "Username Already Exist", "Try Again", JOptionPane.ERROR_MESSAGE);
                    }else{
                        if(password.equals(username)){
                            JOptionPane.showMessageDialog(null, "Password could not be same as Username", "Enter your password again", JOptionPane.ERROR_MESSAGE);
                        }else if(password.length() < 8){
                            JOptionPane.showMessageDialog(null, "Password Must Be 8 character long", "Try Again", JOptionPane.ERROR_MESSAGE);
                        }else if(validPhone(phone)){
                            JOptionPane.showMessageDialog(null, "Enter Valid Phone Number", "Try Again", JOptionPane.ERROR_MESSAGE);
                        }else if(!isValidEmailAddress(email)){
                            JOptionPane.showMessageDialog(null, "Enter Valid email address", "Try Again", JOptionPane.ERROR_MESSAGE);
                        }else{
                            InsertIntoDatabase insDatabase = new InsertIntoDatabase();
                            insDatabase.insertIntoLoginDatabase(fName,lName,gender,address,username,password,email,phone);
                            JOptionPane.showMessageDialog(null, "Registered Sucessfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                            this.dispose();
                            new Login().setVisible(true);
                        }
                    }
                }catch(Exception e){
                    System.out.println("Exception Occured" + e.getMessage());
                } 
            
            }
        }else{
            int n = JOptionPane.showConfirmDialog(null, "Do you want to create database?","No Database Found",JOptionPane.WARNING_MESSAGE);
            if(n == JOptionPane.YES_OPTION){
            CreateDatabase.studentDatabase();
            CreateDatabase.createLoginUsersTable();
            CreateDatabase.createStudentInformationTable();
            JOptionPane.showMessageDialog(null, "Database Created Sucessfully","Success",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnRegisterSignUpActionPerformed

     public static boolean isValidEmailAddress(String email) {
           String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(email);
           return m.matches();
    }
     
    public static boolean validPhone(String phone){
        if (phone.matches("[0-9]+") && phone.length() > 9) {
            return false;
        }else{
            return true;
        }
    }
            
    public boolean checkIfValueCorrect(String fname,String lname,String address,String email,String phone,String username,String password,boolean maleFemale){
        if(fname.equals("")){
            JOptionPane.showMessageDialog(null, "First Name is Empty", "Try Again", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(lname.equals("")){
            JOptionPane.showMessageDialog(null, "Last Name is Empty", "Try Again", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(maleFemale){
            JOptionPane.showMessageDialog(null, "Select Your Gender", "Try Again", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(address.equals("")){
            JOptionPane.showMessageDialog(null, "Address is Empty", "Try Again", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(username.equals("")){
            JOptionPane.showMessageDialog(null, "Username is Empty", "Try Again", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(password.equals("")){
            JOptionPane.showMessageDialog(null, "Password is Empty", "Try Again", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(email.equals("")){
            JOptionPane.showMessageDialog(null, "Email is Empty", "Try Again", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(phone.equals("")){
            JOptionPane.showMessageDialog(null, "Phone is Empty", "Try Again", JOptionPane.ERROR_MESSAGE);
            return false;
        }else{
            return true;
        }
    }
    

    public boolean maleFemale(){
        ButtonGroup bg = new ButtonGroup();
        bg.add(maleSignUp);
        bg.add(femaleSignUp);
        
        if(bg.getSelection()==null){
            return true;
        }else{
            return false;
        }
            
    }
    
    private void btnBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToLoginActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnBackToLoginActionPerformed

    private void maleSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressSignUp;
    private javax.swing.JButton btnBackToLogin;
    private javax.swing.JButton btnRegisterSignUp;
    private javax.swing.JTextField emailSignUp;
    private javax.swing.JTextField fNameSignUp;
    private javax.swing.JRadioButton femaleSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lNameSignUp;
    private javax.swing.JRadioButton maleSignUp;
    private javax.swing.JPasswordField passwordSignUp;
    private javax.swing.JTextField phoneSignUp;
    private javax.swing.JTextField usernameSignUp;
    // End of variables declaration//GEN-END:variables
}
