
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author deepbhai
 */
public class UpdateStudentInformation extends javax.swing.JFrame {
    int getSelectedId;
    /**
     * Creates new form UpdateStudentInformation
     */
    public UpdateStudentInformation() {
        initComponents();
        maleFemale();
        DisplayStudentInformation dsi = new DisplayStudentInformation();
        dsi.findUsers(searchBox.getText(), tableUpdateStudentInformation);
        btnRegisterNUpdateStudentInformation.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fNameUpdateStudentInformation = new javax.swing.JTextField();
        lNameUpdateStudentInformation = new javax.swing.JTextField();
        maleUpdateStudentInformation = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        femaleUpdateStudentInformation = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        addressUpdateStudentInformation = new javax.swing.JTextField();
        emailUpdateStudentInformation = new javax.swing.JTextField();
        phoneUpdateStudentInformation = new javax.swing.JTextField();
        courseUpdateStudentInformation = new javax.swing.JComboBox<>();
        semUpdateStudentInformation = new javax.swing.JComboBox<>();
        btnRegisterNUpdateStudentInformation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUpdateStudentInformation = new javax.swing.JTable();
        searchBox = new javax.swing.JTextField();
        btnSearchUpdateStudentInformation = new javax.swing.JButton();
        btnBackUpdateStudentInformation = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Gender");

        jLabel4.setText("Address");

        jLabel5.setText("Email");

        jLabel6.setText("Phone");

        jLabel7.setText("Course");

        jLabel8.setText("Semester");

        fNameUpdateStudentInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameUpdateStudentInformationActionPerformed(evt);
            }
        });

        lNameUpdateStudentInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameUpdateStudentInformationActionPerformed(evt);
            }
        });

        maleUpdateStudentInformation.setText("Male");
        maleUpdateStudentInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleUpdateStudentInformationActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name");

        femaleUpdateStudentInformation.setText("Female");

        jLabel2.setText("Last Name");

        addressUpdateStudentInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressUpdateStudentInformationActionPerformed(evt);
            }
        });

        emailUpdateStudentInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailUpdateStudentInformationActionPerformed(evt);
            }
        });

        phoneUpdateStudentInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneUpdateStudentInformationActionPerformed(evt);
            }
        });

        courseUpdateStudentInformation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSC CSIT", "BBA", "BBS", "+2" }));

        semUpdateStudentInformation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        btnRegisterNUpdateStudentInformation.setText("Update");
        btnRegisterNUpdateStudentInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterNUpdateStudentInformationActionPerformed(evt);
            }
        });

        tableUpdateStudentInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableUpdateStudentInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUpdateStudentInformationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableUpdateStudentInformation);

        btnSearchUpdateStudentInformation.setText("Search");
        btnSearchUpdateStudentInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchUpdateStudentInformationActionPerformed(evt);
            }
        });

        btnBackUpdateStudentInformation.setText("Back");
        btnBackUpdateStudentInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackUpdateStudentInformationActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setText("*Select Student You Want To Update");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnBackUpdateStudentInformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(phoneUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lNameUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fNameUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(maleUpdateStudentInformation)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(femaleUpdateStudentInformation))
                                                .addComponent(courseUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(semUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(addressUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(emailUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnRegisterNUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnBackUpdateStudentInformation)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fNameUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNameUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maleUpdateStudentInformation)
                    .addComponent(femaleUpdateStudentInformation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(courseUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(semUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnRegisterNUpdateStudentInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fNameUpdateStudentInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameUpdateStudentInformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameUpdateStudentInformationActionPerformed

    private void lNameUpdateStudentInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameUpdateStudentInformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameUpdateStudentInformationActionPerformed

    private void maleUpdateStudentInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleUpdateStudentInformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleUpdateStudentInformationActionPerformed

    private void addressUpdateStudentInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressUpdateStudentInformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressUpdateStudentInformationActionPerformed

    private void emailUpdateStudentInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailUpdateStudentInformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailUpdateStudentInformationActionPerformed

    private void phoneUpdateStudentInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneUpdateStudentInformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneUpdateStudentInformationActionPerformed

    private void btnRegisterNUpdateStudentInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterNUpdateStudentInformationActionPerformed
        // TODO add your handling code here:
        RegisterNewStudent rnw = new RegisterNewStudent();
        int n = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?", "Select an option", JOptionPane.WARNING_MESSAGE);
        if (n == JOptionPane.YES_OPTION){
            String fName = fNameUpdateStudentInformation.getText();
            String lName = lNameUpdateStudentInformation.getText();
            String address = addressUpdateStudentInformation.getText();
            String email = emailUpdateStudentInformation.getText();
            String phone = phoneUpdateStudentInformation.getText();
            String course = (String)courseUpdateStudentInformation.getSelectedItem();
            String semester = (String)semUpdateStudentInformation.getSelectedItem();
            String gender;
            if(maleUpdateStudentInformation.isSelected()){
                gender = maleUpdateStudentInformation.getText();
            }else{
                gender = femaleUpdateStudentInformation.getText();
            }

            boolean maleFemaleCheck = maleFemale();
            if(rnw.checkIfValueCorrect(fName, lName, address, email, phone,maleFemaleCheck)){
                if(!SignUp.isValidEmailAddress(email)){
                    JOptionPane.showMessageDialog(null, "Enter Valid email address", "Try Again", JOptionPane.ERROR_MESSAGE);
                }else if(SignUp.validPhone(phone)){
                    JOptionPane.showMessageDialog(null, "Enter Valid Phone Number", "Try Again", JOptionPane.ERROR_MESSAGE);
                }else{
                    InsertIntoDatabase insDatabase = new InsertIntoDatabase();
                    insDatabase.updateIntoDatabase(getSelectedId,fName,lName,gender,course,semester,address,email,phone);
                    JOptionPane.showMessageDialog(null, "Data Updated Sucessfully", "Sucess", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    new UpdateStudentInformation().setVisible(true);
                }
            } 
        }
        
    }//GEN-LAST:event_btnRegisterNUpdateStudentInformationActionPerformed

    private void btnSearchUpdateStudentInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchUpdateStudentInformationActionPerformed
        // TODO add your handling code here:
        DisplayStudentInformation dsi = new DisplayStudentInformation();
        dsi.findUsers(searchBox.getText(), tableUpdateStudentInformation);
    }//GEN-LAST:event_btnSearchUpdateStudentInformationActionPerformed

    private void btnBackUpdateStudentInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackUpdateStudentInformationActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackUpdateStudentInformationActionPerformed

    private void tableUpdateStudentInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUpdateStudentInformationMouseClicked
        // TODO add your handling code here:
        
        //Get the selected Row Information when clicked
        DefaultTableModel model = (DefaultTableModel) tableUpdateStudentInformation.getModel();
        int selectedRowIndex = tableUpdateStudentInformation.getSelectedRow();
        fNameUpdateStudentInformation.setText(model.getValueAt(selectedRowIndex, 1).toString());
        lNameUpdateStudentInformation.setText(model.getValueAt(selectedRowIndex, 2).toString());
        courseUpdateStudentInformation.setSelectedItem(model.getValueAt(selectedRowIndex, 4));
        String semSel = model.getValueAt(selectedRowIndex, 5).toString();
        semUpdateStudentInformation.setSelectedIndex(Integer.valueOf(semSel)-1);
        addressUpdateStudentInformation.setText(model.getValueAt(selectedRowIndex, 6).toString());
        emailUpdateStudentInformation.setText(model.getValueAt(selectedRowIndex, 7).toString());
        phoneUpdateStudentInformation.setText(model.getValueAt(selectedRowIndex, 8).toString());
        String maleFemale = (String)model.getValueAt(selectedRowIndex, 3);
        //Check the radio button
        if(maleFemale.equals(maleUpdateStudentInformation.getText())){
            maleUpdateStudentInformation.setSelected(true);
        }else{
            femaleUpdateStudentInformation.setSelected(true);
        }
        
        String selectedId = model.getValueAt(selectedRowIndex, 0).toString();
        getSelectedId = Integer.valueOf(selectedId);
        btnRegisterNUpdateStudentInformation.setEnabled(true);
        
        
    }//GEN-LAST:event_tableUpdateStudentInformationMouseClicked
    
    
    public boolean maleFemale(){
        ButtonGroup bg = new ButtonGroup();
        bg.add(maleUpdateStudentInformation);
        bg.add(femaleUpdateStudentInformation);
        if(bg.getSelection() == null){
            return true;
        }else{
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStudentInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressUpdateStudentInformation;
    private javax.swing.JButton btnBackUpdateStudentInformation;
    private javax.swing.JButton btnRegisterNUpdateStudentInformation;
    private javax.swing.JButton btnSearchUpdateStudentInformation;
    private javax.swing.JComboBox<String> courseUpdateStudentInformation;
    private javax.swing.JTextField emailUpdateStudentInformation;
    private javax.swing.JTextField fNameUpdateStudentInformation;
    private javax.swing.JRadioButton femaleUpdateStudentInformation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lNameUpdateStudentInformation;
    private javax.swing.JRadioButton maleUpdateStudentInformation;
    private javax.swing.JTextField phoneUpdateStudentInformation;
    private javax.swing.JTextField searchBox;
    private javax.swing.JComboBox<String> semUpdateStudentInformation;
    private javax.swing.JTable tableUpdateStudentInformation;
    // End of variables declaration//GEN-END:variables
}
